# Generated by Django 5.0.6 on 2025-01-02 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("is_policeman", models.BooleanField(default=False)),
                ("running_for_policeman", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                ("session_id", models.UUIDField(primary_key=True, serialize=False)),
                ("current_phase", models.CharField(max_length=20)),
                ("round_count", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Game",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="PlayerTable",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="game_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.gamesession"
            ),
        ),
    ]
