# Generated by Django 5.1.6 on 2025-02-08 16:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameplayer_gamesession_delete_game_delete_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
